apiVersion: configuration.pipeline-service.io/v1alpha1
kind: SettingsConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 67a0541b.pipeline-service.io
namespace: settings-pipeline-service-controller
networkPolicyConfig:
  namespace: pipeline-service
  spec:
    podSelector:
      matchLabels:
        pipeline-service.io/network-isolation: "true"
    policyTypes:
    - Ingress
    - Egress
quotaConfig:
  namespace: admin
  spec:
    hard:
      count/deployments.apps: "1"
      count/pipelineruns.tekton.dev: "10"
      count/pipelines.tekton.dev: 1k
      count/runs.tekton.dev: "10"
